name: Create Release on Push

on:
  push:
    branches:
      - main # Adjust this to your default branch name

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create annotated tag
        run: git tag -a v${{ github.run_number }} -m "Release version v${{ github.run_number }}"
        if: github.ref == 'refs/heads/main' # Ensure the tag is created only for the main branch

      - name: Push tag
        if: github.ref == 'refs/heads/main' # Ensure the tag is pushed only for the main branch
        run: git push origin --tags

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          draft: false
          prerelease: false
